"""add mhesh tables

Revision ID: 0002_mhesh
Revises: 0001_base
Create Date: 2026-10-02 03:49:15.169493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_mhesh'
down_revision: Union[str, None] = '0001_base'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mhesh_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('rater_kind', sa.String(length=20), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mhesh_ratings_subject_id'), 'mhesh_ratings', ['subject_id'], unique=False)
    op.create_table('mhesh_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('reporter_contact', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mhesh_aspirants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('official_name', sa.String(length=200), nullable=True),
    sa.Column('title_prefix', sa.String(length=20), nullable=True),
    sa.Column('photo_r2_key', sa.String(length=500), nullable=True),
    sa.Column('party', sa.String(length=100), nullable=True),
    sa.Column('office', sa.Enum('president', 'governor', 'senator', 'woman_rep', 'mp', 'mca', name='mhesh_office'), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=False),
    sa.Column('constituency', sa.String(length=100), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('manifesto', sa.JSON(), nullable=False),
    sa.Column('achievements', sa.JSON(), nullable=False),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.Column('whatsapp_public', sa.String(length=20), nullable=True),
    sa.Column('verified_mpesa', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'verified', 'featured', 'setup', name='mhesh_aspirant_tier'), nullable=False),
    sa.Column('featured_until', sa.DateTime(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('whatsapp_click_count', sa.Integer(), nullable=False),
    sa.Column('lora_key', sa.String(length=500), nullable=True),
    sa.Column('lora_trained_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mhesh_aspirants_county'), 'mhesh_aspirants', ['county'], unique=False)
    op.create_index(op.f('ix_mhesh_aspirants_office'), 'mhesh_aspirants', ['office'], unique=False)
    op.create_index(op.f('ix_mhesh_aspirants_slug'), 'mhesh_aspirants', ['slug'], unique=True)
    op.create_index(op.f('ix_mhesh_aspirants_user_id'), 'mhesh_aspirants', ['user_id'], unique=True)
    op.create_table('mhesh_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pricing', sa.JSON(), nullable=False),
    sa.Column('capacity_per_day', sa.Integer(), nullable=True),
    sa.Column('turnaround_days', sa.Integer(), nullable=True),
    sa.Column('sample_urls', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', name='mhesh_partner_status'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('orders_completed', sa.Integer(), nullable=False),
    sa.Column('orders_disputed', sa.Integer(), nullable=False),
    sa.Column('featured_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mhesh_partners_county'), 'mhesh_partners', ['county'], unique=False)
    op.create_index(op.f('ix_mhesh_partners_phone'), 'mhesh_partners', ['phone'], unique=False)
    op.create_index(op.f('ix_mhesh_partners_slug'), 'mhesh_partners', ['slug'], unique=True)
    op.create_index(op.f('ix_mhesh_partners_status'), 'mhesh_partners', ['status'], unique=False)
    op.create_index(op.f('ix_mhesh_partners_user_id'), 'mhesh_partners', ['user_id'], unique=False)
    op.create_table('mhesh_supporters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('verified_mpesa', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('trust_computed_at', sa.DateTime(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_disputed', sa.Integer(), nullable=False),
    sa.Column('total_earned_kes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mhesh_supporters_phone'), 'mhesh_supporters', ['phone'], unique=False)
    op.create_index(op.f('ix_mhesh_supporters_user_id'), 'mhesh_supporters', ['user_id'], unique=True)
    op.create_table('mhesh_ai_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aspirant_id', sa.UUID(), nullable=False),
    sa.Column('style_template', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('output_urls', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('lora_key', sa.String(length=500), nullable=True),
    sa.Column('cost_kes', sa.Integer(), nullable=False),
    sa.Column('generation_ms', sa.Integer(), nullable=False),
    sa.Column('audit_metadata', sa.JSON(), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aspirant_id'], ['mhesh_aspirants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mhesh_ai_generations_aspirant_id'), 'mhesh_ai_generations', ['aspirant_id'], unique=False)
    op.create_index(op.f('ix_mhesh_ai_generations_created_at'), 'mhesh_ai_generations', ['created_at'], unique=False)
    op.create_table('mhesh_escrow',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.Column('aspirant_id', sa.UUID(), nullable=False),
    sa.Column('campaign_account_ref', sa.String(length=100), nullable=True),
    sa.Column('amount_kes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'funded', 'released', 'refunded', 'disputed', name='mhesh_escrow_status'), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('mpesa_receipt', sa.String(length=50), nullable=True),
    sa.Column('released_to_phone', sa.String(length=20), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('b2c_receipt', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aspirant_id'], ['mhesh_aspirants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mhesh_escrow_aspirant_id'), 'mhesh_escrow', ['aspirant_id'], unique=False)
    op.create_index(op.f('ix_mhesh_escrow_checkout_request_id'), 'mhesh_escrow', ['checkout_request_id'], unique=False)
    op.create_index(op.f('ix_mhesh_escrow_mpesa_receipt'), 'mhesh_escrow', ['mpesa_receipt'], unique=False)
    op.create_index(op.f('ix_mhesh_escrow_ref_id'), 'mhesh_escrow', ['ref_id'], unique=False)
    op.create_index(op.f('ix_mhesh_escrow_status'), 'mhesh_escrow', ['status'], unique=False)
    op.create_table('mhesh_followers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aspirant_id', sa.UUID(), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('contact_kind', sa.String(length=10), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verify_token', sa.String(length=64), nullable=True),
    sa.Column('unsub_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aspirant_id'], ['mhesh_aspirants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unsub_token')
    )
    op.create_index(op.f('ix_mhesh_followers_aspirant_id'), 'mhesh_followers', ['aspirant_id'], unique=False)
    op.create_index(op.f('ix_mhesh_followers_contact'), 'mhesh_followers', ['contact'], unique=False)
    op.create_index(op.f('ix_mhesh_followers_verify_token'), 'mhesh_followers', ['verify_token'], unique=False)
    op.create_table('mhesh_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aspirant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('print_merchandise', 'distribute_posters', 'distribute_merch', 'event_staffing', 'digital_amplification', 'canvassing', name='mhesh_task_category'), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('reward_kes', sa.Integer(), nullable=False),
    sa.Column('escrow_fee_kes', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'funded', 'published', 'assigned', 'completed', 'approved', 'disputed', 'cancelled', name='mhesh_task_status'), nullable=False),
    sa.Column('assigned_supporter_id', sa.UUID(), nullable=True),
    sa.Column('evidence_urls', sa.JSON(), nullable=False),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('verification_flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aspirant_id'], ['mhesh_aspirants.id'], ),
    sa.ForeignKeyConstraint(['assigned_supporter_id'], ['mhesh_supporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mhesh_tasks_aspirant_id'), 'mhesh_tasks', ['aspirant_id'], unique=False)
    op.create_index(op.f('ix_mhesh_tasks_category'), 'mhesh_tasks', ['category'], unique=False)
    op.create_index(op.f('ix_mhesh_tasks_status'), 'mhesh_tasks', ['status'], unique=False)
    op.create_table('mhesh_print_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aspirant_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('design_url', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit_price_kes', sa.Integer(), nullable=False),
    sa.Column('total_kes', sa.Integer(), nullable=False),
    sa.Column('referral_fee_kes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'funded', 'in_production', 'shipped', 'delivered', 'approved', 'disputed', name='mhesh_order_status'), nullable=False),
    sa.Column('escrow_id', sa.UUID(), nullable=True),
    sa.Column('delivery_evidence_urls', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aspirant_id'], ['mhesh_aspirants.id'], ),
    sa.ForeignKeyConstraint(['escrow_id'], ['mhesh_escrow.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['mhesh_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mhesh_print_orders_aspirant_id'), 'mhesh_print_orders', ['aspirant_id'], unique=False)
    op.create_index(op.f('ix_mhesh_print_orders_partner_id'), 'mhesh_print_orders', ['partner_id'], unique=False)
    op.create_index(op.f('ix_mhesh_print_orders_status'), 'mhesh_print_orders', ['status'], unique=False)
    op.create_table('mhesh_task_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('supporter_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supporter_id'], ['mhesh_supporters.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['mhesh_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mhesh_task_applications_supporter_id'), 'mhesh_task_applications', ['supporter_id'], unique=False)
    op.create_index(op.f('ix_mhesh_task_applications_task_id'), 'mhesh_task_applications', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mhesh_task_applications_task_id'), table_name='mhesh_task_applications')
    op.drop_index(op.f('ix_mhesh_task_applications_supporter_id'), table_name='mhesh_task_applications')
    op.drop_table('mhesh_task_applications')
    op.drop_index(op.f('ix_mhesh_print_orders_status'), table_name='mhesh_print_orders')
    op.drop_index(op.f('ix_mhesh_print_orders_partner_id'), table_name='mhesh_print_orders')
    op.drop_index(op.f('ix_mhesh_print_orders_aspirant_id'), table_name='mhesh_print_orders')
    op.drop_table('mhesh_print_orders')
    op.drop_index(op.f('ix_mhesh_tasks_status'), table_name='mhesh_tasks')
    op.drop_index(op.f('ix_mhesh_tasks_category'), table_name='mhesh_tasks')
    op.drop_index(op.f('ix_mhesh_tasks_aspirant_id'), table_name='mhesh_tasks')
    op.drop_table('mhesh_tasks')
    op.drop_index(op.f('ix_mhesh_followers_verify_token'), table_name='mhesh_followers')
    op.drop_index(op.f('ix_mhesh_followers_contact'), table_name='mhesh_followers')
    op.drop_index(op.f('ix_mhesh_followers_aspirant_id'), table_name='mhesh_followers')
    op.drop_table('mhesh_followers')
    op.drop_index(op.f('ix_mhesh_escrow_status'), table_name='mhesh_escrow')
    op.drop_index(op.f('ix_mhesh_escrow_ref_id'), table_name='mhesh_escrow')
    op.drop_index(op.f('ix_mhesh_escrow_mpesa_receipt'), table_name='mhesh_escrow')
    op.drop_index(op.f('ix_mhesh_escrow_checkout_request_id'), table_name='mhesh_escrow')
    op.drop_index(op.f('ix_mhesh_escrow_aspirant_id'), table_name='mhesh_escrow')
    op.drop_table('mhesh_escrow')
    op.drop_index(op.f('ix_mhesh_ai_generations_created_at'), table_name='mhesh_ai_generations')
    op.drop_index(op.f('ix_mhesh_ai_generations_aspirant_id'), table_name='mhesh_ai_generations')
    op.drop_table('mhesh_ai_generations')
    op.drop_index(op.f('ix_mhesh_supporters_user_id'), table_name='mhesh_supporters')
    op.drop_index(op.f('ix_mhesh_supporters_phone'), table_name='mhesh_supporters')
    op.drop_table('mhesh_supporters')
    op.drop_index(op.f('ix_mhesh_partners_user_id'), table_name='mhesh_partners')
    op.drop_index(op.f('ix_mhesh_partners_status'), table_name='mhesh_partners')
    op.drop_index(op.f('ix_mhesh_partners_slug'), table_name='mhesh_partners')
    op.drop_index(op.f('ix_mhesh_partners_phone'), table_name='mhesh_partners')
    op.drop_index(op.f('ix_mhesh_partners_county'), table_name='mhesh_partners')
    op.drop_table('mhesh_partners')
    op.drop_index(op.f('ix_mhesh_aspirants_user_id'), table_name='mhesh_aspirants')
    op.drop_index(op.f('ix_mhesh_aspirants_slug'), table_name='mhesh_aspirants')
    op.drop_index(op.f('ix_mhesh_aspirants_office'), table_name='mhesh_aspirants')
    op.drop_index(op.f('ix_mhesh_aspirants_county'), table_name='mhesh_aspirants')
    op.drop_table('mhesh_aspirants')
    op.drop_table('mhesh_reports')
    op.drop_index(op.f('ix_mhesh_ratings_subject_id'), table_name='mhesh_ratings')
    op.drop_table('mhesh_ratings')
    # ### end Alembic commands ###
    for enum_name in ("mhesh_office", "mhesh_aspirant_tier", "mhesh_task_status", "mhesh_task_category",
                      "mhesh_escrow_status", "mhesh_partner_status", "mhesh_order_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
